### ISSUE TITLE
Error when deploying on HuggingFace

### ISSUE THREAD

**Issue by rileynjohnson** [EleutherAI/rnngineering#1]
Hey yall, very excited about what you're doing.  Ran into an error trying to deploy with HuggingFace and I suspect I'm not alone. To really get RWKV to spread, you want your huggingface experience to be frictionless for users:

[huggingface rwkv error log.txt](https://github.com/EleutherAI/rnn-engineering/files/14226888/huggingface.rwkv.error.log.txt)

https://huggingface.co/RWKV/v5-Eagle-7B

**Comment by Quentin-Anthony** [comment]
@blinkdl @picocreator
